<?php
/**
 * AttributesApi
 * PHP version 7.2
 *
 * @category Class
 * @package  KauflandSellerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.14.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KauflandSellerApi\Api;

use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Query;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use KauflandSellerApi\ApiException;
use KauflandSellerApi\Configuration;
use KauflandSellerApi\DebugPlugin;
use KauflandSellerApi\HeaderSelector;
use KauflandSellerApi\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;

use function sprintf;

/**
 * AttributesApi Class Doc Comment
 *
 * @category Class
 * @package  KauflandSellerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttributesApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ClientInterface $httpClient = null,
        Configuration $config = null,
        HttpAsyncClient $httpAsyncClient = null,
        UriFactoryInterface $uriFactory = null,
        RequestFactoryInterface $requestFactory = null,
        StreamFactoryInterface $streamFactory = null,
        HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('/v2');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAttribute
     *
     * Get attribute by ID
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseAttribute|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\NotFoundResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getAttribute($id_attribute, $storefront, $locale = null)
    {
        list($response) = $this->getAttributeWithHttpInfo($id_attribute, $storefront, $locale);
        return $response;
    }

    /**
     * Operation getAttributeWithHttpInfo
     *
     * Get attribute by ID
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseAttribute|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\NotFoundResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAttributeWithHttpInfo($id_attribute, $storefront, $locale = null)
    {
        $request = $this->getAttributeRequest($id_attribute, $storefront, $locale);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\ApiResponseAttribute' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseAttribute', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\KauflandSellerApi\Model\NotFoundResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\NotFoundResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseAttribute';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseAttribute',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\NotFoundResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAttributeAsync
     *
     * Get attribute by ID
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getAttributeAsync($id_attribute, $storefront, $locale = null)
    {
        return $this->getAttributeAsyncWithHttpInfo($id_attribute, $storefront, $locale)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAttributeAsyncWithHttpInfo
     *
     * Get attribute by ID
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getAttributeAsyncWithHttpInfo($id_attribute, $storefront, $locale = null)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseAttribute';
        $request = $this->getAttributeRequest($id_attribute, $storefront, $locale);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAttribute'
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getAttributeRequest($id_attribute, $storefront, $locale = null)
    {
        // verify the required parameter 'id_attribute' is set
        if ($id_attribute === null || (is_array($id_attribute) && count($id_attribute) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_attribute when calling getAttribute'
            );
        }
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling getAttribute'
            );
        }

        $resourcePath = '/attributes/{id_attribute}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }
        // query params
        if ($locale !== null) {
            if('form' === 'form' && is_array($locale)) {
                foreach($locale as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['locale'] = $locale;
            }
        }

        // path params
        if ($id_attribute !== null) {
            $resourcePath = str_replace(
                '{' . 'id_attribute' . '}',
                ObjectSerializer::toPathValue($id_attribute),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getAttributeByName
     *
     * Get attribute by name
     *
     * @param  string $name The name of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseAttribute|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\NotFoundResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getAttributeByName($name, $storefront, $locale = null)
    {
        list($response) = $this->getAttributeByNameWithHttpInfo($name, $storefront, $locale);
        return $response;
    }

    /**
     * Operation getAttributeByNameWithHttpInfo
     *
     * Get attribute by name
     *
     * @param  string $name The name of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseAttribute|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\NotFoundResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAttributeByNameWithHttpInfo($name, $storefront, $locale = null)
    {
        $request = $this->getAttributeByNameRequest($name, $storefront, $locale);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\ApiResponseAttribute' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseAttribute', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\KauflandSellerApi\Model\NotFoundResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\NotFoundResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseAttribute';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseAttribute',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\NotFoundResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAttributeByNameAsync
     *
     * Get attribute by name
     *
     * @param  string $name The name of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getAttributeByNameAsync($name, $storefront, $locale = null)
    {
        return $this->getAttributeByNameAsyncWithHttpInfo($name, $storefront, $locale)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAttributeByNameAsyncWithHttpInfo
     *
     * Get attribute by name
     *
     * @param  string $name The name of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getAttributeByNameAsyncWithHttpInfo($name, $storefront, $locale = null)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseAttribute';
        $request = $this->getAttributeByNameRequest($name, $storefront, $locale);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAttributeByName'
     *
     * @param  string $name The name of the attribute (required)
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getAttributeByNameRequest($name, $storefront, $locale = null)
    {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getAttributeByName'
            );
        }
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling getAttributeByName'
            );
        }

        $resourcePath = '/attributes/by-name/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }
        // query params
        if ($locale !== null) {
            if('form' === 'form' && is_array($locale)) {
                foreach($locale as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['locale'] = $locale;
            }
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getAttributeList
     *
     * Get an attribute list
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\CollectionApiResponseAttribute|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getAttributeList($storefront, $limit = null, $offset = null, $locale = null)
    {
        list($response) = $this->getAttributeListWithHttpInfo($storefront, $limit, $offset, $locale);
        return $response;
    }

    /**
     * Operation getAttributeListWithHttpInfo
     *
     * Get an attribute list
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\CollectionApiResponseAttribute|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAttributeListWithHttpInfo($storefront, $limit = null, $offset = null, $locale = null)
    {
        $request = $this->getAttributeListRequest($storefront, $limit, $offset, $locale);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\CollectionApiResponseAttribute' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\CollectionApiResponseAttribute', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\CollectionApiResponseAttribute';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\CollectionApiResponseAttribute',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAttributeListAsync
     *
     * Get an attribute list
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getAttributeListAsync($storefront, $limit = null, $offset = null, $locale = null)
    {
        return $this->getAttributeListAsyncWithHttpInfo($storefront, $limit, $offset, $locale)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAttributeListAsyncWithHttpInfo
     *
     * Get an attribute list
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getAttributeListAsyncWithHttpInfo($storefront, $limit = null, $offset = null, $locale = null)
    {
        $returnType = '\KauflandSellerApi\Model\CollectionApiResponseAttribute';
        $request = $this->getAttributeListRequest($storefront, $limit, $offset, $locale);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAttributeList'
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getAttributeListRequest($storefront, $limit = null, $offset = null, $locale = null)
    {
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling getAttributeList'
            );
        }
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling AttributesApi.getAttributeList, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling AttributesApi.getAttributeList, must be bigger than or equal to 0.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling AttributesApi.getAttributeList, must be bigger than or equal to 0.');
        }

        $resourcePath = '/attributes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }
        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if('form' === 'form' && is_array($offset)) {
                foreach($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['offset'] = $offset;
            }
        }
        // query params
        if ($locale !== null) {
            if('form' === 'form' && is_array($locale)) {
                foreach($locale as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['locale'] = $locale;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getAttributeListBySearch
     *
     * Get attributes by search term
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  string $q Search term for finding a specific attribute (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\CollectionApiResponseAttribute|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getAttributeListBySearch($storefront, $q, $limit = null, $offset = null, $locale = null)
    {
        list($response) = $this->getAttributeListBySearchWithHttpInfo($storefront, $q, $limit, $offset, $locale);
        return $response;
    }

    /**
     * Operation getAttributeListBySearchWithHttpInfo
     *
     * Get attributes by search term
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  string $q Search term for finding a specific attribute (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\CollectionApiResponseAttribute|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAttributeListBySearchWithHttpInfo($storefront, $q, $limit = null, $offset = null, $locale = null)
    {
        $request = $this->getAttributeListBySearchRequest($storefront, $q, $limit, $offset, $locale);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\CollectionApiResponseAttribute' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\CollectionApiResponseAttribute', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\CollectionApiResponseAttribute';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\CollectionApiResponseAttribute',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAttributeListBySearchAsync
     *
     * Get attributes by search term
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  string $q Search term for finding a specific attribute (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getAttributeListBySearchAsync($storefront, $q, $limit = null, $offset = null, $locale = null)
    {
        return $this->getAttributeListBySearchAsyncWithHttpInfo($storefront, $q, $limit, $offset, $locale)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAttributeListBySearchAsyncWithHttpInfo
     *
     * Get attributes by search term
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  string $q Search term for finding a specific attribute (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getAttributeListBySearchAsyncWithHttpInfo($storefront, $q, $limit = null, $offset = null, $locale = null)
    {
        $returnType = '\KauflandSellerApi\Model\CollectionApiResponseAttribute';
        $request = $this->getAttributeListBySearchRequest($storefront, $q, $limit, $offset, $locale);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAttributeListBySearch'
     *
     * @param  Storefront $storefront Specifies the store by country (required)
     * @param  string $q Search term for finding a specific attribute (required)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getAttributeListBySearchRequest($storefront, $q, $limit = null, $offset = null, $locale = null)
    {
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling getAttributeListBySearch'
            );
        }
        // verify the required parameter 'q' is set
        if ($q === null || (is_array($q) && count($q) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $q when calling getAttributeListBySearch'
            );
        }
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling AttributesApi.getAttributeListBySearch, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling AttributesApi.getAttributeListBySearch, must be bigger than or equal to 0.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling AttributesApi.getAttributeListBySearch, must be bigger than or equal to 0.');
        }

        $resourcePath = '/attributes/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }
        // query params
        if ($q !== null) {
            if('form' === 'form' && is_array($q)) {
                foreach($q as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['q'] = $q;
            }
        }
        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if('form' === 'form' && is_array($offset)) {
                foreach($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['offset'] = $offset;
            }
        }
        // query params
        if ($locale !== null) {
            if('form' === 'form' && is_array($locale)) {
                foreach($locale as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['locale'] = $locale;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getSharedSetListBySearchAndAttributeId
     *
     * Get shared-set by search term and attribute id
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (required)
     * @param  string $q Search term for finding a specific shared set value (optional)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\CollectionApiResponseSharedSet|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getSharedSetListBySearchAndAttributeId($id_attribute, $locale, $q = null, $limit = null, $offset = null)
    {
        list($response) = $this->getSharedSetListBySearchAndAttributeIdWithHttpInfo($id_attribute, $locale, $q, $limit, $offset);
        return $response;
    }

    /**
     * Operation getSharedSetListBySearchAndAttributeIdWithHttpInfo
     *
     * Get shared-set by search term and attribute id
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (required)
     * @param  string $q Search term for finding a specific shared set value (optional)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\CollectionApiResponseSharedSet|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedSetListBySearchAndAttributeIdWithHttpInfo($id_attribute, $locale, $q = null, $limit = null, $offset = null)
    {
        $request = $this->getSharedSetListBySearchAndAttributeIdRequest($id_attribute, $locale, $q, $limit, $offset);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\CollectionApiResponseSharedSet' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\CollectionApiResponseSharedSet', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\CollectionApiResponseSharedSet';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\CollectionApiResponseSharedSet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSharedSetListBySearchAndAttributeIdAsync
     *
     * Get shared-set by search term and attribute id
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (required)
     * @param  string $q Search term for finding a specific shared set value (optional)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getSharedSetListBySearchAndAttributeIdAsync($id_attribute, $locale, $q = null, $limit = null, $offset = null)
    {
        return $this->getSharedSetListBySearchAndAttributeIdAsyncWithHttpInfo($id_attribute, $locale, $q, $limit, $offset)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSharedSetListBySearchAndAttributeIdAsyncWithHttpInfo
     *
     * Get shared-set by search term and attribute id
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (required)
     * @param  string $q Search term for finding a specific shared set value (optional)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getSharedSetListBySearchAndAttributeIdAsyncWithHttpInfo($id_attribute, $locale, $q = null, $limit = null, $offset = null)
    {
        $returnType = '\KauflandSellerApi\Model\CollectionApiResponseSharedSet';
        $request = $this->getSharedSetListBySearchAndAttributeIdRequest($id_attribute, $locale, $q, $limit, $offset);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSharedSetListBySearchAndAttributeId'
     *
     * @param  int $id_attribute The ID of the attribute (required)
     * @param  ProductDataLocale $locale Allows clients to consume the data in languages that are different from the storefront-default locale (required)
     * @param  string $q Search term for finding a specific shared set value (optional)
     * @param  int $limit Desired size of result set. Max: 100 (optional)
     * @param  int $offset Offset applied to result set (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getSharedSetListBySearchAndAttributeIdRequest($id_attribute, $locale, $q = null, $limit = null, $offset = null)
    {
        // verify the required parameter 'id_attribute' is set
        if ($id_attribute === null || (is_array($id_attribute) && count($id_attribute) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_attribute when calling getSharedSetListBySearchAndAttributeId'
            );
        }
        // verify the required parameter 'locale' is set
        if ($locale === null || (is_array($locale) && count($locale) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $locale when calling getSharedSetListBySearchAndAttributeId'
            );
        }
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling AttributesApi.getSharedSetListBySearchAndAttributeId, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling AttributesApi.getSharedSetListBySearchAndAttributeId, must be bigger than or equal to 1.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling AttributesApi.getSharedSetListBySearchAndAttributeId, must be bigger than or equal to 0.');
        }

        $resourcePath = '/attributes/{id_attribute}/shared-set';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($locale !== null) {
            if('form' === 'form' && is_array($locale)) {
                foreach($locale as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['locale'] = $locale;
            }
        }
        // query params
        if ($q !== null) {
            if('form' === 'form' && is_array($q)) {
                foreach($q as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['q'] = $q;
            }
        }
        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if('form' === 'form' && is_array($offset)) {
                foreach($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['offset'] = $offset;
            }
        }

        // path params
        if ($id_attribute !== null) {
            $resourcePath = str_replace(
                '{' . 'id_attribute' . '}',
                ObjectSerializer::toPathValue($id_attribute),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(Query::build($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }
}
