<?php
/**
 * OrderUnitsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  KauflandSellerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.14.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KauflandSellerApi\Api;

use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Query;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use KauflandSellerApi\ApiException;
use KauflandSellerApi\Configuration;
use KauflandSellerApi\DebugPlugin;
use KauflandSellerApi\HeaderSelector;
use KauflandSellerApi\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;

use function sprintf;

/**
 * OrderUnitsApi Class Doc Comment
 *
 * @category Class
 * @package  KauflandSellerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderUnitsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ClientInterface $httpClient = null,
        Configuration $config = null,
        HttpAsyncClient $httpAsyncClient = null,
        UriFactoryInterface $uriFactory = null,
        RequestFactoryInterface $requestFactory = null,
        StreamFactoryInterface $streamFactory = null,
        HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('/v2');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation cancelOrderUnit
     *
     * Cancel an order unit
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitCancelRequest $order_unit_cancel_request Reason of the cancellation (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function cancelOrderUnit($id_order_unit, $order_unit_cancel_request)
    {
        $this->cancelOrderUnitWithHttpInfo($id_order_unit, $order_unit_cancel_request);
    }

    /**
     * Operation cancelOrderUnitWithHttpInfo
     *
     * Cancel an order unit
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitCancelRequest $order_unit_cancel_request Reason of the cancellation (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelOrderUnitWithHttpInfo($id_order_unit, $order_unit_cancel_request)
    {
        $request = $this->cancelOrderUnitRequest($id_order_unit, $order_unit_cancel_request);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation cancelOrderUnitAsync
     *
     * Cancel an order unit
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitCancelRequest $order_unit_cancel_request Reason of the cancellation (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function cancelOrderUnitAsync($id_order_unit, $order_unit_cancel_request)
    {
        return $this->cancelOrderUnitAsyncWithHttpInfo($id_order_unit, $order_unit_cancel_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cancelOrderUnitAsyncWithHttpInfo
     *
     * Cancel an order unit
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitCancelRequest $order_unit_cancel_request Reason of the cancellation (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function cancelOrderUnitAsyncWithHttpInfo($id_order_unit, $order_unit_cancel_request)
    {
        $returnType = '';
        $request = $this->cancelOrderUnitRequest($id_order_unit, $order_unit_cancel_request);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'cancelOrderUnit'
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitCancelRequest $order_unit_cancel_request Reason of the cancellation (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function cancelOrderUnitRequest($id_order_unit, $order_unit_cancel_request)
    {
        // verify the required parameter 'id_order_unit' is set
        if ($id_order_unit === null || (is_array($id_order_unit) && count($id_order_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_order_unit when calling cancelOrderUnit'
            );
        }
        // verify the required parameter 'order_unit_cancel_request' is set
        if ($order_unit_cancel_request === null || (is_array($order_unit_cancel_request) && count($order_unit_cancel_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_unit_cancel_request when calling cancelOrderUnit'
            );
        }

        $resourcePath = '/order-units/{id_order_unit}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($id_order_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_order_unit' . '}',
                ObjectSerializer::toPathValue($id_order_unit),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($order_unit_cancel_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($order_unit_cancel_request));
            } else {
                $httpBody = $order_unit_cancel_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }

    /**
     * Operation fulfilOrderUnit
     *
     * Mark an order unit to be in fulfillment
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function fulfilOrderUnit($id_order_unit)
    {
        $this->fulfilOrderUnitWithHttpInfo($id_order_unit);
    }

    /**
     * Operation fulfilOrderUnitWithHttpInfo
     *
     * Mark an order unit to be in fulfillment
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function fulfilOrderUnitWithHttpInfo($id_order_unit)
    {
        $request = $this->fulfilOrderUnitRequest($id_order_unit);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation fulfilOrderUnitAsync
     *
     * Mark an order unit to be in fulfillment
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function fulfilOrderUnitAsync($id_order_unit)
    {
        return $this->fulfilOrderUnitAsyncWithHttpInfo($id_order_unit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation fulfilOrderUnitAsyncWithHttpInfo
     *
     * Mark an order unit to be in fulfillment
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function fulfilOrderUnitAsyncWithHttpInfo($id_order_unit)
    {
        $returnType = '';
        $request = $this->fulfilOrderUnitRequest($id_order_unit);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'fulfilOrderUnit'
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function fulfilOrderUnitRequest($id_order_unit)
    {
        // verify the required parameter 'id_order_unit' is set
        if ($id_order_unit === null || (is_array($id_order_unit) && count($id_order_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_order_unit when calling fulfilOrderUnit'
            );
        }

        $resourcePath = '/order-units/{id_order_unit}/fulfil';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($id_order_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_order_unit' . '}',
                ObjectSerializer::toPathValue($id_order_unit),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }

    /**
     * Operation getOrderUnit
     *
     * Get an order unit by ID
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseOrderUnitDetails|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getOrderUnit($id_order_unit, $embedded = null)
    {
        list($response) = $this->getOrderUnitWithHttpInfo($id_order_unit, $embedded);
        return $response;
    }

    /**
     * Operation getOrderUnitWithHttpInfo
     *
     * Get an order unit by ID
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseOrderUnitDetails|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrderUnitWithHttpInfo($id_order_unit, $embedded = null)
    {
        $request = $this->getOrderUnitRequest($id_order_unit, $embedded);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\ApiResponseOrderUnitDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseOrderUnitDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseOrderUnitDetails';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseOrderUnitDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getOrderUnitAsync
     *
     * Get an order unit by ID
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getOrderUnitAsync($id_order_unit, $embedded = null)
    {
        return $this->getOrderUnitAsyncWithHttpInfo($id_order_unit, $embedded)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrderUnitAsyncWithHttpInfo
     *
     * Get an order unit by ID
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getOrderUnitAsyncWithHttpInfo($id_order_unit, $embedded = null)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseOrderUnitDetails';
        $request = $this->getOrderUnitRequest($id_order_unit, $embedded);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrderUnit'
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getOrderUnitRequest($id_order_unit, $embedded = null)
    {
        // verify the required parameter 'id_order_unit' is set
        if ($id_order_unit === null || (is_array($id_order_unit) && count($id_order_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_order_unit when calling getOrderUnit'
            );
        }

        $resourcePath = '/order-units/{id_order_unit}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($embedded !== null) {
            if('form' === 'form' && is_array($embedded)) {
                foreach($embedded as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['embedded'] = $embedded;
            }
        }

        // path params
        if ($id_order_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_order_unit' . '}',
                ObjectSerializer::toPathValue($id_order_unit),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getOrderUnits
     *
     * Get a list of order units
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  string $id_offer Unique ID for offer(s) (optional)
     * @param  \KauflandSellerApi\Model\OrderUnitStatus[] $status Get only order units which are in the given status (optional)
     * @param  \DateTime $ts_created_from_iso Get only order units which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only order units which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only order units which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\CollectionApiResponseOrderUnit|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getOrderUnits($storefront = null, $id_offer = null, $status = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        list($response) = $this->getOrderUnitsWithHttpInfo($storefront, $id_offer, $status, $ts_created_from_iso, $ts_updated_from_iso, $fulfillment_type, $sort, $limit, $offset);
        return $response;
    }

    /**
     * Operation getOrderUnitsWithHttpInfo
     *
     * Get a list of order units
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  string $id_offer Unique ID for offer(s) (optional)
     * @param  \KauflandSellerApi\Model\OrderUnitStatus[] $status Get only order units which are in the given status (optional)
     * @param  \DateTime $ts_created_from_iso Get only order units which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only order units which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only order units which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\CollectionApiResponseOrderUnit|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrderUnitsWithHttpInfo($storefront = null, $id_offer = null, $status = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        $request = $this->getOrderUnitsRequest($storefront, $id_offer, $status, $ts_created_from_iso, $ts_updated_from_iso, $fulfillment_type, $sort, $limit, $offset);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\CollectionApiResponseOrderUnit' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\CollectionApiResponseOrderUnit', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\CollectionApiResponseOrderUnit';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\CollectionApiResponseOrderUnit',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getOrderUnitsAsync
     *
     * Get a list of order units
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  string $id_offer Unique ID for offer(s) (optional)
     * @param  \KauflandSellerApi\Model\OrderUnitStatus[] $status Get only order units which are in the given status (optional)
     * @param  \DateTime $ts_created_from_iso Get only order units which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only order units which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only order units which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getOrderUnitsAsync($storefront = null, $id_offer = null, $status = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        return $this->getOrderUnitsAsyncWithHttpInfo($storefront, $id_offer, $status, $ts_created_from_iso, $ts_updated_from_iso, $fulfillment_type, $sort, $limit, $offset)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrderUnitsAsyncWithHttpInfo
     *
     * Get a list of order units
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  string $id_offer Unique ID for offer(s) (optional)
     * @param  \KauflandSellerApi\Model\OrderUnitStatus[] $status Get only order units which are in the given status (optional)
     * @param  \DateTime $ts_created_from_iso Get only order units which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only order units which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only order units which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getOrderUnitsAsyncWithHttpInfo($storefront = null, $id_offer = null, $status = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        $returnType = '\KauflandSellerApi\Model\CollectionApiResponseOrderUnit';
        $request = $this->getOrderUnitsRequest($storefront, $id_offer, $status, $ts_created_from_iso, $ts_updated_from_iso, $fulfillment_type, $sort, $limit, $offset);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrderUnits'
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  string $id_offer Unique ID for offer(s) (optional)
     * @param  \KauflandSellerApi\Model\OrderUnitStatus[] $status Get only order units which are in the given status (optional)
     * @param  \DateTime $ts_created_from_iso Get only order units which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only order units which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only order units which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getOrderUnitsRequest($storefront = null, $id_offer = null, $status = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling OrderUnitsApi.getOrderUnits, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling OrderUnitsApi.getOrderUnits, must be bigger than or equal to 1.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling OrderUnitsApi.getOrderUnits, must be bigger than or equal to 0.');
        }

        $resourcePath = '/order-units';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }
        // query params
        if ($id_offer !== null) {
            if('form' === 'form' && is_array($id_offer)) {
                foreach($id_offer as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['id_offer'] = $id_offer;
            }
        }
        // query params
        if ($status !== null) {
            if('form' === 'form' && is_array($status)) {
                foreach($status as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['status'] = $status;
            }
        }
        // query params
        if ($ts_created_from_iso !== null) {
            if('form' === 'form' && is_array($ts_created_from_iso)) {
                foreach($ts_created_from_iso as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['ts_created_from_iso'] = $ts_created_from_iso;
            }
        }
        // query params
        if ($ts_updated_from_iso !== null) {
            if('form' === 'form' && is_array($ts_updated_from_iso)) {
                foreach($ts_updated_from_iso as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['ts_updated_from_iso'] = $ts_updated_from_iso;
            }
        }
        // query params
        if ($fulfillment_type !== null) {
            if('form' === 'form' && is_array($fulfillment_type)) {
                foreach($fulfillment_type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['fulfillment_type'] = $fulfillment_type;
            }
        }
        // query params
        if ($sort !== null) {
            if('form' === 'form' && is_array($sort)) {
                foreach($sort as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['sort'] = $sort;
            }
        }
        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if('form' === 'form' && is_array($offset)) {
                foreach($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['offset'] = $offset;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation refundOrderUnit
     *
     * Send a refund to a customer
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitRefundRequest $order_unit_refund_request Request body containing amount and reason of the refund. (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function refundOrderUnit($id_order_unit, $order_unit_refund_request)
    {
        $this->refundOrderUnitWithHttpInfo($id_order_unit, $order_unit_refund_request);
    }

    /**
     * Operation refundOrderUnitWithHttpInfo
     *
     * Send a refund to a customer
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitRefundRequest $order_unit_refund_request Request body containing amount and reason of the refund. (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function refundOrderUnitWithHttpInfo($id_order_unit, $order_unit_refund_request)
    {
        $request = $this->refundOrderUnitRequest($id_order_unit, $order_unit_refund_request);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation refundOrderUnitAsync
     *
     * Send a refund to a customer
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitRefundRequest $order_unit_refund_request Request body containing amount and reason of the refund. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function refundOrderUnitAsync($id_order_unit, $order_unit_refund_request)
    {
        return $this->refundOrderUnitAsyncWithHttpInfo($id_order_unit, $order_unit_refund_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation refundOrderUnitAsyncWithHttpInfo
     *
     * Send a refund to a customer
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitRefundRequest $order_unit_refund_request Request body containing amount and reason of the refund. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function refundOrderUnitAsyncWithHttpInfo($id_order_unit, $order_unit_refund_request)
    {
        $returnType = '';
        $request = $this->refundOrderUnitRequest($id_order_unit, $order_unit_refund_request);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'refundOrderUnit'
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitRefundRequest $order_unit_refund_request Request body containing amount and reason of the refund. (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function refundOrderUnitRequest($id_order_unit, $order_unit_refund_request)
    {
        // verify the required parameter 'id_order_unit' is set
        if ($id_order_unit === null || (is_array($id_order_unit) && count($id_order_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_order_unit when calling refundOrderUnit'
            );
        }
        // verify the required parameter 'order_unit_refund_request' is set
        if ($order_unit_refund_request === null || (is_array($order_unit_refund_request) && count($order_unit_refund_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_unit_refund_request when calling refundOrderUnit'
            );
        }

        $resourcePath = '/order-units/{id_order_unit}/refund';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($id_order_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_order_unit' . '}',
                ObjectSerializer::toPathValue($id_order_unit),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($order_unit_refund_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($order_unit_refund_request));
            } else {
                $httpBody = $order_unit_refund_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }

    /**
     * Operation sendOrderUnit
     *
     * Mark an order unit as sent
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitSendRequest $order_unit_send_request Request body containing tracking number(s) and carrier code of the shipment(s) (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function sendOrderUnit($id_order_unit, $order_unit_send_request)
    {
        $this->sendOrderUnitWithHttpInfo($id_order_unit, $order_unit_send_request);
    }

    /**
     * Operation sendOrderUnitWithHttpInfo
     *
     * Mark an order unit as sent
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitSendRequest $order_unit_send_request Request body containing tracking number(s) and carrier code of the shipment(s) (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendOrderUnitWithHttpInfo($id_order_unit, $order_unit_send_request)
    {
        $request = $this->sendOrderUnitRequest($id_order_unit, $order_unit_send_request);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendOrderUnitAsync
     *
     * Mark an order unit as sent
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitSendRequest $order_unit_send_request Request body containing tracking number(s) and carrier code of the shipment(s) (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sendOrderUnitAsync($id_order_unit, $order_unit_send_request)
    {
        return $this->sendOrderUnitAsyncWithHttpInfo($id_order_unit, $order_unit_send_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendOrderUnitAsyncWithHttpInfo
     *
     * Mark an order unit as sent
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitSendRequest $order_unit_send_request Request body containing tracking number(s) and carrier code of the shipment(s) (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sendOrderUnitAsyncWithHttpInfo($id_order_unit, $order_unit_send_request)
    {
        $returnType = '';
        $request = $this->sendOrderUnitRequest($id_order_unit, $order_unit_send_request);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendOrderUnit'
     *
     * @param  int $id_order_unit Order unit ID, unique across all order units (required)
     * @param  \KauflandSellerApi\Model\OrderUnitSendRequest $order_unit_send_request Request body containing tracking number(s) and carrier code of the shipment(s) (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function sendOrderUnitRequest($id_order_unit, $order_unit_send_request)
    {
        // verify the required parameter 'id_order_unit' is set
        if ($id_order_unit === null || (is_array($id_order_unit) && count($id_order_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_order_unit when calling sendOrderUnit'
            );
        }
        // verify the required parameter 'order_unit_send_request' is set
        if ($order_unit_send_request === null || (is_array($order_unit_send_request) && count($order_unit_send_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_unit_send_request when calling sendOrderUnit'
            );
        }

        $resourcePath = '/order-units/{id_order_unit}/send';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($id_order_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_order_unit' . '}',
                ObjectSerializer::toPathValue($id_order_unit),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($order_unit_send_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($order_unit_send_request));
            } else {
                $httpBody = $order_unit_send_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }

    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(Query::build($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }
}
