<?php
/**
 * ReturnsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  KauflandSellerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.17.2
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KauflandSellerApi\Api;

use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Query;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use KauflandSellerApi\ApiException;
use KauflandSellerApi\Configuration;
use KauflandSellerApi\DebugPlugin;
use KauflandSellerApi\HeaderSelector;
use KauflandSellerApi\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;

use function sprintf;

/**
 * ReturnsApi Class Doc Comment
 *
 * @category Class
 * @package  KauflandSellerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReturnsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ClientInterface $httpClient = null,
        Configuration $config = null,
        HttpAsyncClient $httpAsyncClient = null,
        UriFactoryInterface $uriFactory = null,
        RequestFactoryInterface $requestFactory = null,
        StreamFactoryInterface $streamFactory = null,
        HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('/v2');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getReturn
     *
     * Get a return by ID
     *
     * @param  int $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\ReturnEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseReturnDetails|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getReturn($id_return, $embedded = null)
    {
        list($response) = $this->getReturnWithHttpInfo($id_return, $embedded);
        return $response;
    }

    /**
     * Operation getReturnWithHttpInfo
     *
     * Get a return by ID
     *
     * @param  int $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\ReturnEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseReturnDetails|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getReturnWithHttpInfo($id_return, $embedded = null)
    {
        $request = $this->getReturnRequest($id_return, $embedded);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\ApiResponseReturnDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseReturnDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseReturnDetails';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseReturnDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getReturnAsync
     *
     * Get a return by ID
     *
     * @param  int $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\ReturnEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getReturnAsync($id_return, $embedded = null)
    {
        return $this->getReturnAsyncWithHttpInfo($id_return, $embedded)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getReturnAsyncWithHttpInfo
     *
     * Get a return by ID
     *
     * @param  int $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\ReturnEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getReturnAsyncWithHttpInfo($id_return, $embedded = null)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseReturnDetails';
        $request = $this->getReturnRequest($id_return, $embedded);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getReturn'
     *
     * @param  int $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\ReturnEmbeddable[] $embedded Additional data to be returned (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getReturnRequest($id_return, $embedded = null)
    {
        // verify the required parameter 'id_return' is set
        if ($id_return === null || (is_array($id_return) && count($id_return) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_return when calling getReturn'
            );
        }

        $resourcePath = '/returns/{id_return}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($embedded !== null) {
            if ('form' === 'form' && is_array($embedded)) {
                foreach ($embedded as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['embedded'] = $embedded;
            }
        }

        // path params
        if ($id_return !== null) {
            $resourcePath = str_replace(
                '{' . 'id_return' . '}',
                ObjectSerializer::toPathValue($id_return),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getReturns
     *
     * Get a list of returns
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  \DateTime $ts_created_from_iso Get only returns which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only returns which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  string $tracking_code The tracking code of a particular return (optional)
     * @param  \KauflandSellerApi\Model\ReturnStatus[] $status Get only returns which are in the given status (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only returns which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\CollectionApiResponseReturn|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getReturns($storefront = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $tracking_code = null, $status = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        list($response) = $this->getReturnsWithHttpInfo($storefront, $ts_created_from_iso, $ts_updated_from_iso, $tracking_code, $status, $fulfillment_type, $sort, $limit, $offset);
        return $response;
    }

    /**
     * Operation getReturnsWithHttpInfo
     *
     * Get a list of returns
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  \DateTime $ts_created_from_iso Get only returns which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only returns which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  string $tracking_code The tracking code of a particular return (optional)
     * @param  \KauflandSellerApi\Model\ReturnStatus[] $status Get only returns which are in the given status (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only returns which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\CollectionApiResponseReturn|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getReturnsWithHttpInfo($storefront = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $tracking_code = null, $status = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        $request = $this->getReturnsRequest($storefront, $ts_created_from_iso, $ts_updated_from_iso, $tracking_code, $status, $fulfillment_type, $sort, $limit, $offset);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\CollectionApiResponseReturn' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\CollectionApiResponseReturn', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\CollectionApiResponseReturn';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\CollectionApiResponseReturn',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getReturnsAsync
     *
     * Get a list of returns
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  \DateTime $ts_created_from_iso Get only returns which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only returns which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  string $tracking_code The tracking code of a particular return (optional)
     * @param  \KauflandSellerApi\Model\ReturnStatus[] $status Get only returns which are in the given status (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only returns which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getReturnsAsync($storefront = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $tracking_code = null, $status = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        return $this->getReturnsAsyncWithHttpInfo($storefront, $ts_created_from_iso, $ts_updated_from_iso, $tracking_code, $status, $fulfillment_type, $sort, $limit, $offset)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getReturnsAsyncWithHttpInfo
     *
     * Get a list of returns
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  \DateTime $ts_created_from_iso Get only returns which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only returns which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  string $tracking_code The tracking code of a particular return (optional)
     * @param  \KauflandSellerApi\Model\ReturnStatus[] $status Get only returns which are in the given status (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only returns which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getReturnsAsyncWithHttpInfo($storefront = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $tracking_code = null, $status = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        $returnType = '\KauflandSellerApi\Model\CollectionApiResponseReturn';
        $request = $this->getReturnsRequest($storefront, $ts_created_from_iso, $ts_updated_from_iso, $tracking_code, $status, $fulfillment_type, $sort, $limit, $offset);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getReturns'
     *
     * @param  Storefront $storefront Locale of storefront (optional)
     * @param  \DateTime $ts_created_from_iso Get only returns which were placed after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  \DateTime $ts_updated_from_iso Get only returns which were updated after this timestamp. Should be in YYYY-MM-ddTHH:mm:ssZ format (optional)
     * @param  string $tracking_code The tracking code of a particular return (optional)
     * @param  \KauflandSellerApi\Model\ReturnStatus[] $status Get only returns which are in the given status (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only returns which are fulfilled by the given type (optional)
     * @param  string $sort Specify sorting (optional, default to 'ts_created:desc')
     * @param  int $limit Desired size of result set&lt;br&gt;max: 100, default: 30 (optional, default to 30)
     * @param  int $offset Offset applied to result set&lt;br&gt;default: 0 (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getReturnsRequest($storefront = null, $ts_created_from_iso = null, $ts_updated_from_iso = null, $tracking_code = null, $status = null, $fulfillment_type = null, $sort = 'ts_created:desc', $limit = 30, $offset = 0)
    {
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ReturnsApi.getReturns, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ReturnsApi.getReturns, must be bigger than or equal to 1.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling ReturnsApi.getReturns, must be bigger than or equal to 0.');
        }

        $resourcePath = '/returns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if ('form' === 'form' && is_array($storefront)) {
                foreach ($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }
        // query params
        if ($ts_created_from_iso !== null) {
            if ('form' === 'form' && is_array($ts_created_from_iso)) {
                foreach ($ts_created_from_iso as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['ts_created_from_iso'] = $ts_created_from_iso;
            }
        }
        // query params
        if ($ts_updated_from_iso !== null) {
            if ('form' === 'form' && is_array($ts_updated_from_iso)) {
                foreach ($ts_updated_from_iso as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['ts_updated_from_iso'] = $ts_updated_from_iso;
            }
        }
        // query params
        if ($tracking_code !== null) {
            if ('form' === 'form' && is_array($tracking_code)) {
                foreach ($tracking_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['tracking_code'] = $tracking_code;
            }
        }
        // query params
        if ($status !== null) {
            if ('form' === 'form' && is_array($status)) {
                foreach ($status as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['status'] = $status;
            }
        }
        // query params
        if ($fulfillment_type !== null) {
            if ('form' === 'form' && is_array($fulfillment_type)) {
                foreach ($fulfillment_type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['fulfillment_type'] = $fulfillment_type;
            }
        }
        // query params
        if ($sort !== null) {
            if ('form' === 'form' && is_array($sort)) {
                foreach ($sort as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['sort'] = $sort;
            }
        }
        // query params
        if ($limit !== null) {
            if ('form' === 'form' && is_array($limit)) {
                foreach ($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if ('form' === 'form' && is_array($offset)) {
                foreach ($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['offset'] = $offset;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation initiateReturn
     *
     * Initialize a return
     *
     * @param  \KauflandSellerApi\Model\InitializeReturnRequest[] $initialize_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseInitializeReturn|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function initiateReturn($initialize_return_request)
    {
        list($response) = $this->initiateReturnWithHttpInfo($initialize_return_request);
        return $response;
    }

    /**
     * Operation initiateReturnWithHttpInfo
     *
     * Initialize a return
     *
     * @param  \KauflandSellerApi\Model\InitializeReturnRequest[] $initialize_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseInitializeReturn|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function initiateReturnWithHttpInfo($initialize_return_request)
    {
        $request = $this->initiateReturnRequest($initialize_return_request);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 201:
                    if ('\KauflandSellerApi\Model\ApiResponseInitializeReturn' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseInitializeReturn', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseInitializeReturn';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseInitializeReturn',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation initiateReturnAsync
     *
     * Initialize a return
     *
     * @param  \KauflandSellerApi\Model\InitializeReturnRequest[] $initialize_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function initiateReturnAsync($initialize_return_request)
    {
        return $this->initiateReturnAsyncWithHttpInfo($initialize_return_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation initiateReturnAsyncWithHttpInfo
     *
     * Initialize a return
     *
     * @param  \KauflandSellerApi\Model\InitializeReturnRequest[] $initialize_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function initiateReturnAsyncWithHttpInfo($initialize_return_request)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseInitializeReturn';
        $request = $this->initiateReturnRequest($initialize_return_request);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'initiateReturn'
     *
     * @param  \KauflandSellerApi\Model\InitializeReturnRequest[] $initialize_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function initiateReturnRequest($initialize_return_request)
    {
        // verify the required parameter 'initialize_return_request' is set
        if ($initialize_return_request === null || (is_array($initialize_return_request) && count($initialize_return_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $initialize_return_request when calling initiateReturn'
            );
        }

        $resourcePath = '/returns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($initialize_return_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($initialize_return_request));
            } else {
                $httpBody = $initialize_return_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation updateReturn
     *
     * Add one or more order units to an already existing return
     *
     * @param  string $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\UpdateReturnRequest[] $update_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseUpdateReturn|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function updateReturn($id_return, $update_return_request)
    {
        list($response) = $this->updateReturnWithHttpInfo($id_return, $update_return_request);
        return $response;
    }

    /**
     * Operation updateReturnWithHttpInfo
     *
     * Add one or more order units to an already existing return
     *
     * @param  string $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\UpdateReturnRequest[] $update_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseUpdateReturn|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateReturnWithHttpInfo($id_return, $update_return_request)
    {
        $request = $this->updateReturnRequest($id_return, $update_return_request);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 201:
                    if ('\KauflandSellerApi\Model\ApiResponseUpdateReturn' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseUpdateReturn', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseUpdateReturn';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseUpdateReturn',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateReturnAsync
     *
     * Add one or more order units to an already existing return
     *
     * @param  string $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\UpdateReturnRequest[] $update_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function updateReturnAsync($id_return, $update_return_request)
    {
        return $this->updateReturnAsyncWithHttpInfo($id_return, $update_return_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateReturnAsyncWithHttpInfo
     *
     * Add one or more order units to an already existing return
     *
     * @param  string $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\UpdateReturnRequest[] $update_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function updateReturnAsyncWithHttpInfo($id_return, $update_return_request)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseUpdateReturn';
        $request = $this->updateReturnRequest($id_return, $update_return_request);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateReturn'
     *
     * @param  string $id_return Return ID, unique across all returns (required)
     * @param  \KauflandSellerApi\Model\UpdateReturnRequest[] $update_return_request Request body containing return data for one or more order units (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function updateReturnRequest($id_return, $update_return_request)
    {
        // verify the required parameter 'id_return' is set
        if ($id_return === null || (is_array($id_return) && count($id_return) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_return when calling updateReturn'
            );
        }
        // verify the required parameter 'update_return_request' is set
        if ($update_return_request === null || (is_array($update_return_request) && count($update_return_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_return_request when calling updateReturn'
            );
        }

        $resourcePath = '/returns/{id_return}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($id_return !== null) {
            $resourcePath = str_replace(
                '{' . 'id_return' . '}',
                ObjectSerializer::toPathValue($id_return),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($update_return_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($update_return_request));
            } else {
                $httpBody = $update_return_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }

    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(Query::build($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }
}
