<?php
/**
 * UnitsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  KauflandSellerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * The version of the OpenAPI document: 2.14.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KauflandSellerApi\Api;

use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Query;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use KauflandSellerApi\ApiException;
use KauflandSellerApi\Configuration;
use KauflandSellerApi\DebugPlugin;
use KauflandSellerApi\HeaderSelector;
use KauflandSellerApi\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;

use function sprintf;

/**
 * UnitsApi Class Doc Comment
 *
 * @category Class
 * @package  KauflandSellerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UnitsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ClientInterface $httpClient = null,
        Configuration $config = null,
        HttpAsyncClient $httpAsyncClient = null,
        UriFactoryInterface $uriFactory = null,
        RequestFactoryInterface $requestFactory = null,
        StreamFactoryInterface $streamFactory = null,
        HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('/v2');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bulkUpdateUnits
     *
     * Update some fields of a given set of units
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitsBulkUpdateRequest[] $units_bulk_update_request Update Object (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\UnitsBulkUpdateResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function bulkUpdateUnits($storefront, $units_bulk_update_request)
    {
        list($response) = $this->bulkUpdateUnitsWithHttpInfo($storefront, $units_bulk_update_request);
        return $response;
    }

    /**
     * Operation bulkUpdateUnitsWithHttpInfo
     *
     * Update some fields of a given set of units
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitsBulkUpdateRequest[] $units_bulk_update_request Update Object (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\UnitsBulkUpdateResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function bulkUpdateUnitsWithHttpInfo($storefront, $units_bulk_update_request)
    {
        $request = $this->bulkUpdateUnitsRequest($storefront, $units_bulk_update_request);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 207:
                    if ('\KauflandSellerApi\Model\UnitsBulkUpdateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\UnitsBulkUpdateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\UnitsBulkUpdateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 207:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\UnitsBulkUpdateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bulkUpdateUnitsAsync
     *
     * Update some fields of a given set of units
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitsBulkUpdateRequest[] $units_bulk_update_request Update Object (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function bulkUpdateUnitsAsync($storefront, $units_bulk_update_request)
    {
        return $this->bulkUpdateUnitsAsyncWithHttpInfo($storefront, $units_bulk_update_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bulkUpdateUnitsAsyncWithHttpInfo
     *
     * Update some fields of a given set of units
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitsBulkUpdateRequest[] $units_bulk_update_request Update Object (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function bulkUpdateUnitsAsyncWithHttpInfo($storefront, $units_bulk_update_request)
    {
        $returnType = '\KauflandSellerApi\Model\UnitsBulkUpdateResponse';
        $request = $this->bulkUpdateUnitsRequest($storefront, $units_bulk_update_request);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'bulkUpdateUnits'
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitsBulkUpdateRequest[] $units_bulk_update_request Update Object (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function bulkUpdateUnitsRequest($storefront, $units_bulk_update_request)
    {
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling bulkUpdateUnits'
            );
        }
        // verify the required parameter 'units_bulk_update_request' is set
        if ($units_bulk_update_request === null || (is_array($units_bulk_update_request) && count($units_bulk_update_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $units_bulk_update_request when calling bulkUpdateUnits'
            );
        }

        $resourcePath = '/units/bulk';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($units_bulk_update_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($units_bulk_update_request));
            } else {
                $httpBody = $units_bulk_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation createUnit
     *
     * Add a unit
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitRequest $unit_request Information about the unit that will be generated (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseUnit|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function createUnit($storefront, $unit_request)
    {
        list($response) = $this->createUnitWithHttpInfo($storefront, $unit_request);
        return $response;
    }

    /**
     * Operation createUnitWithHttpInfo
     *
     * Add a unit
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitRequest $unit_request Information about the unit that will be generated (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseUnit|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createUnitWithHttpInfo($storefront, $unit_request)
    {
        $request = $this->createUnitRequest($storefront, $unit_request);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\ApiResponseUnit' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseUnit', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseUnit';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseUnit',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createUnitAsync
     *
     * Add a unit
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitRequest $unit_request Information about the unit that will be generated (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function createUnitAsync($storefront, $unit_request)
    {
        return $this->createUnitAsyncWithHttpInfo($storefront, $unit_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createUnitAsyncWithHttpInfo
     *
     * Add a unit
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitRequest $unit_request Information about the unit that will be generated (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function createUnitAsyncWithHttpInfo($storefront, $unit_request)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseUnit';
        $request = $this->createUnitRequest($storefront, $unit_request);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'createUnit'
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitRequest $unit_request Information about the unit that will be generated (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function createUnitRequest($storefront, $unit_request)
    {
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling createUnit'
            );
        }
        // verify the required parameter 'unit_request' is set
        if ($unit_request === null || (is_array($unit_request) && count($unit_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $unit_request when calling createUnit'
            );
        }

        $resourcePath = '/units';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($unit_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($unit_request));
            } else {
                $httpBody = $unit_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation deleteUnit
     *
     * Delete a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteUnit($id_unit, $storefront)
    {
        $this->deleteUnitWithHttpInfo($id_unit, $storefront);
    }

    /**
     * Operation deleteUnitWithHttpInfo
     *
     * Delete a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteUnitWithHttpInfo($id_unit, $storefront)
    {
        $request = $this->deleteUnitRequest($id_unit, $storefront);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteUnitAsync
     *
     * Delete a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deleteUnitAsync($id_unit, $storefront)
    {
        return $this->deleteUnitAsyncWithHttpInfo($id_unit, $storefront)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteUnitAsyncWithHttpInfo
     *
     * Delete a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function deleteUnitAsyncWithHttpInfo($id_unit, $storefront)
    {
        $returnType = '';
        $request = $this->deleteUnitRequest($id_unit, $storefront);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteUnit'
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function deleteUnitRequest($id_unit, $storefront)
    {
        // verify the required parameter 'id_unit' is set
        if ($id_unit === null || (is_array($id_unit) && count($id_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_unit when calling deleteUnit'
            );
        }
        if ($id_unit < 1) {
            throw new \InvalidArgumentException('invalid value for "$id_unit" when calling UnitsApi.deleteUnit, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling deleteUnit'
            );
        }

        $resourcePath = '/units/{id_unit}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }

        // path params
        if ($id_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_unit' . '}',
                ObjectSerializer::toPathValue($id_unit),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('DELETE', $uri, $headers, $httpBody);
    }

    /**
     * Operation getUnit
     *
     * Get a unit by ID
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded embedded (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseUnit|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getUnit($id_unit, $storefront, $embedded = null)
    {
        list($response) = $this->getUnitWithHttpInfo($id_unit, $storefront, $embedded);
        return $response;
    }

    /**
     * Operation getUnitWithHttpInfo
     *
     * Get a unit by ID
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseUnit|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUnitWithHttpInfo($id_unit, $storefront, $embedded = null)
    {
        $request = $this->getUnitRequest($id_unit, $storefront, $embedded);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\ApiResponseUnit' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseUnit', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseUnit';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseUnit',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUnitAsync
     *
     * Get a unit by ID
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getUnitAsync($id_unit, $storefront, $embedded = null)
    {
        return $this->getUnitAsyncWithHttpInfo($id_unit, $storefront, $embedded)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUnitAsyncWithHttpInfo
     *
     * Get a unit by ID
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getUnitAsyncWithHttpInfo($id_unit, $storefront, $embedded = null)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseUnit';
        $request = $this->getUnitRequest($id_unit, $storefront, $embedded);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUnit'
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getUnitRequest($id_unit, $storefront, $embedded = null)
    {
        // verify the required parameter 'id_unit' is set
        if ($id_unit === null || (is_array($id_unit) && count($id_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_unit when calling getUnit'
            );
        }
        if ($id_unit < 1) {
            throw new \InvalidArgumentException('invalid value for "$id_unit" when calling UnitsApi.getUnit, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling getUnit'
            );
        }

        $resourcePath = '/units/{id_unit}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }
        // query params
        if ($embedded !== null) {
            if('form' === 'form' && is_array($embedded)) {
                foreach($embedded as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['embedded'] = $embedded;
            }
        }

        // path params
        if ($id_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_unit' . '}',
                ObjectSerializer::toPathValue($id_unit),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation getUnits
     *
     * Get a list of your units
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded embedded (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\CollectionApiResponseUnitEmbedded|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function getUnits($storefront, $limit = 30, $offset = 0, $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = null)
    {
        list($response) = $this->getUnitsWithHttpInfo($storefront, $limit, $offset, $id_offer, $id_product, $ean, $embedded, $fulfillment_type);
        return $response;
    }

    /**
     * Operation getUnitsWithHttpInfo
     *
     * Get a list of your units
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\CollectionApiResponseUnitEmbedded|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUnitsWithHttpInfo($storefront, $limit = 30, $offset = 0, $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = null)
    {
        $request = $this->getUnitsRequest($storefront, $limit, $offset, $id_offer, $id_product, $ean, $embedded, $fulfillment_type);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\CollectionApiResponseUnitEmbedded' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\CollectionApiResponseUnitEmbedded', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\CollectionApiResponseUnitEmbedded';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\CollectionApiResponseUnitEmbedded',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUnitsAsync
     *
     * Get a list of your units
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getUnitsAsync($storefront, $limit = 30, $offset = 0, $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = null)
    {
        return $this->getUnitsAsyncWithHttpInfo($storefront, $limit, $offset, $id_offer, $id_product, $ean, $embedded, $fulfillment_type)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUnitsAsyncWithHttpInfo
     *
     * Get a list of your units
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function getUnitsAsyncWithHttpInfo($storefront, $limit = 30, $offset = 0, $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = null)
    {
        $returnType = '\KauflandSellerApi\Model\CollectionApiResponseUnitEmbedded';
        $request = $this->getUnitsRequest($storefront, $limit, $offset, $id_offer, $id_product, $ean, $embedded, $fulfillment_type);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUnits'
     *
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \KauflandSellerApi\Model\UnitEmbeddedEnum[] $embedded (optional)
     * @param  \KauflandSellerApi\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function getUnitsRequest($storefront, $limit = 30, $offset = 0, $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = null)
    {
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling getUnits'
            );
        }
        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling UnitsApi.getUnits, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling UnitsApi.getUnits, must be bigger than or equal to 0.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling UnitsApi.getUnits, must be bigger than or equal to 0.');
        }

        if ($id_product !== null && $id_product < 1) {
            throw new \InvalidArgumentException('invalid value for "$id_product" when calling UnitsApi.getUnits, must be bigger than or equal to 1.');
        }

        $resourcePath = '/units';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if('form' === 'form' && is_array($offset)) {
                foreach($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['offset'] = $offset;
            }
        }
        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }
        // query params
        if ($id_offer !== null) {
            if('form' === 'form' && is_array($id_offer)) {
                foreach($id_offer as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['id_offer'] = $id_offer;
            }
        }
        // query params
        if ($id_product !== null) {
            if('form' === 'form' && is_array($id_product)) {
                foreach($id_product as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['id_product'] = $id_product;
            }
        }
        // query params
        if ($ean !== null) {
            if('form' === 'form' && is_array($ean)) {
                foreach($ean as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['ean'] = $ean;
            }
        }
        // query params
        if ($embedded !== null) {
            if('form' === 'form' && is_array($embedded)) {
                foreach($embedded as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['embedded'] = $embedded;
            }
        }
        // query params
        if ($fulfillment_type !== null) {
            if('form' === 'form' && is_array($fulfillment_type)) {
                foreach($fulfillment_type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['fulfillment_type'] = $fulfillment_type;
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation patchUnit
     *
     * Update some of the fields of a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitPatchRequest $unit_patch_request Update Object (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KauflandSellerApi\Model\ApiResponseUnit|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse
     */
    public function patchUnit($id_unit, $storefront, $unit_patch_request)
    {
        list($response) = $this->patchUnitWithHttpInfo($id_unit, $storefront, $unit_patch_request);
        return $response;
    }

    /**
     * Operation patchUnitWithHttpInfo
     *
     * Update some of the fields of a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitPatchRequest $unit_patch_request Update Object (required)
     *
     * @throws \KauflandSellerApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KauflandSellerApi\Model\ApiResponseUnit|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse|\KauflandSellerApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchUnitWithHttpInfo($id_unit, $storefront, $unit_patch_request)
    {
        $request = $this->patchUnitRequest($id_unit, $storefront, $unit_patch_request);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    if ('\KauflandSellerApi\Model\ApiResponseUnit' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ApiResponseUnit', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\KauflandSellerApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\KauflandSellerApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\KauflandSellerApi\Model\ApiResponseUnit';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ApiResponseUnit',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KauflandSellerApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation patchUnitAsync
     *
     * Update some of the fields of a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitPatchRequest $unit_patch_request Update Object (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function patchUnitAsync($id_unit, $storefront, $unit_patch_request)
    {
        return $this->patchUnitAsyncWithHttpInfo($id_unit, $storefront, $unit_patch_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchUnitAsyncWithHttpInfo
     *
     * Update some of the fields of a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitPatchRequest $unit_patch_request Update Object (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function patchUnitAsyncWithHttpInfo($id_unit, $storefront, $unit_patch_request)
    {
        $returnType = '\KauflandSellerApi\Model\ApiResponseUnit';
        $request = $this->patchUnitRequest($id_unit, $storefront, $unit_patch_request);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchUnit'
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \KauflandSellerApi\Model\UnitPatchRequest $unit_patch_request Update Object (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function patchUnitRequest($id_unit, $storefront, $unit_patch_request)
    {
        // verify the required parameter 'id_unit' is set
        if ($id_unit === null || (is_array($id_unit) && count($id_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_unit when calling patchUnit'
            );
        }
        if ($id_unit < 1) {
            throw new \InvalidArgumentException('invalid value for "$id_unit" when calling UnitsApi.patchUnit, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling patchUnit'
            );
        }
        // verify the required parameter 'unit_patch_request' is set
        if ($unit_patch_request === null || (is_array($unit_patch_request) && count($unit_patch_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $unit_patch_request when calling patchUnit'
            );
        }

        $resourcePath = '/units/{id_unit}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($storefront !== null) {
            if('form' === 'form' && is_array($storefront)) {
                foreach($storefront as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['storefront'] = $storefront;
            }
        }

        // path params
        if ($id_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_unit' . '}',
                ObjectSerializer::toPathValue($id_unit),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($unit_patch_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($unit_patch_request));
            } else {
                $httpBody = $unit_patch_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = Query::build($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }

    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(Query::build($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }
}
